### ISSUE TITLE
Problem launchip app.js

### ISSUE THREAD

**Issue by Cusu95** [Blooware/jarvis#3]
Hi!
I'm trying to launch the js file, but it gives me this error:
internal/modules/cjs/loader.js:267
    throw e;
    ^

SyntaxError: Error parsing /Users/Andrea/Downloads/jarvis-master/package.json: Unexpected token } in JSON at position 384
    at parse (<anonymous>)
    at readPackage (internal/modules/cjs/loader.js:254:20)
    at readPackageScope (internal/modules/cjs/loader.js:279:19)
    at shouldUseESMLoader (internal/modules/run_main.js:36:15)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:67:24)
    at internal/main/run_main_module.js:17:47 {

Do you have any idea why?

**Comment by abedshaaban** [comment]
@Cusu95  did you install the needed dependencies? if not run "npm i" to install the needed dependencies and packages form the package.json file.

hope this helps
